apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{.Iteration}}
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Mangaal/argocd-performance-test
    targetRevision: HEAD
    path: test-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test-{{.Iteration}}
  syncPolicy:
    automated: {}