apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: argocd-test-optimize-{{.Iteration}}
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
