apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: argocd-test-{{.Iteration}}
subjects:
  - kind: ServiceAccount
    name: <application-controller-service-account-name>
    namespace: <argocd-namespace>
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
